<?php

return [

[
function() {
$_SESSION['field0'] = \App\Models\ProductField::create(['name' => 'Region-0', 'in_table' => true]);
$_SESSION['field1'] = \App\Models\ProductField::create(['name' => 'Region-1', 'in_table' => true]);
$_SESSION['field2'] = \App\Models\ProductField::create(['name' => 'Region-2', 'in_table' => true]);
$_SESSION['field3'] = \App\Models\ProductField::create(['name' => 'Region-3', 'in_table' => true]);
$_SESSION['field4'] = \App\Models\ProductField::create(['name' => 'Region-4', 'in_table' => true]);
$_SESSION['field5'] = \App\Models\ProductField::create(['name' => 'Region-5', 'in_table' => true]);
}
],
[
function() {
$option0 = \App\Models\ProductFieldOption::create(['name' => 'Dark Orange','value' => '#88532F','additional_price' => 0]);
$option1 = \App\Models\ProductFieldOption::create(['name' => 'Medium Brown','value' => '#948575','additional_price' => 0]);
$option2 = \App\Models\ProductFieldOption::create(['name' => 'Dark Brown','value' => '#594E41','additional_price' => 0]);
$option3 = \App\Models\ProductFieldOption::create(['name' => 'DarkWolfFur','value' => '#887666','additional_price' => 0]);
$option4 = \App\Models\ProductFieldOption::create(['name' => 'DragonBase0','value' => '#A0664B','additional_price' => 0]);
$option5 = \App\Models\ProductFieldOption::create(['name' => 'DragonBase1','value' => '#CB7956','additional_price' => 0]);
$option6 = \App\Models\ProductFieldOption::create(['name' => 'WyvernPurple0','value' => '#787496','additional_price' => 0]);
$option7 = \App\Models\ProductFieldOption::create(['name' => 'Light Grey','value' => '#C8CACA','additional_price' => 0]);
$option8 = \App\Models\ProductFieldOption::create(['name' => 'Dark Grey','value' => '#7B7B7B','additional_price' => 0]);
$option9 = \App\Models\ProductFieldOption::create(['name' => 'Black','value' => '#3B3B3B','additional_price' => 0]);
$option10 = \App\Models\ProductFieldOption::create(['name' => 'Dark Red','value' => '#592B2B','additional_price' => 0]);
$option11 = \App\Models\ProductFieldOption::create(['name' => 'Light Orange','value' => '#FFB694','additional_price' => 0]);
$option12 = \App\Models\ProductFieldOption::create(['name' => 'Light Yellow','value' => '#CACAA0','additional_price' => 0]);
$option13 = \App\Models\ProductFieldOption::create(['name' => 'Dark Yellow','value' => '#94946C','additional_price' => 0]);
$option14 = \App\Models\ProductFieldOption::create(['name' => 'Light Green','value' => '#E0FFE0','additional_price' => 0]);
$option15 = \App\Models\ProductFieldOption::create(['name' => 'Medium Green','value' => '#799479','additional_price' => 0]);
$option16 = \App\Models\ProductFieldOption::create(['name' => 'Dark Green','value' => '#224122','additional_price' => 0]);
$option17 = \App\Models\ProductFieldOption::create(['name' => 'Light Brown','value' => '#FFE0BA','additional_price' => 0]);
$option18 = \App\Models\ProductFieldOption::create(['name' => 'Darker Grey','value' => '#595959','additional_price' => 0]);
$option19 = \App\Models\ProductFieldOption::create(['name' => 'Dark Blue','value' => '#394263','additional_price' => 0]);
$option20 = \App\Models\ProductFieldOption::create(['name' => 'Dark Purple','value' => '#403459','additional_price' => 0]);
$option21 = \App\Models\ProductFieldOption::create(['name' => 'Red','value' => '#FF0000','additional_price' => 0]);
$option22 = \App\Models\ProductFieldOption::create(['name' => 'Blue','value' => '#0000FF','additional_price' => 0]);
$option23 = \App\Models\ProductFieldOption::create(['name' => 'Green','value' => '#00FF00','additional_price' => 0]);
$option24 = \App\Models\ProductFieldOption::create(['name' => 'Yellow','value' => '#FFFF00','additional_price' => 0]);
$option25 = \App\Models\ProductFieldOption::create(['name' => 'Light Red','value' => '#FFA8A8','additional_price' => 0]);
$option26 = \App\Models\ProductFieldOption::create(['name' => 'Light Blue','value' => '#D9E0FF','additional_price' => 0]);
$option27 = \App\Models\ProductFieldOption::create(['name' => 'Light Purple','value' => '#E4D9FF','additional_price' => 0]);
$option28 = \App\Models\ProductFieldOption::create(['name' => 'Albino','value' => '#FFFFFF','additional_price' => 0]);
$option29 = \App\Models\ProductFieldOption::create(['name' => 'Orange','value' => '#FF7F00','additional_price' => 0]);
$option30 = \App\Models\ProductFieldOption::create(['name' => 'White','value' => '#FFFFFF','additional_price' => 0]);
$option31 = \App\Models\ProductFieldOption::create(['name' => 'BigFoot5','value' => '#D0A794','additional_price' => 0]);
$option32 = \App\Models\ProductFieldOption::create(['name' => 'WolfFur','value' => '#C3B39F','additional_price' => 0]);
$option33 = \App\Models\ProductFieldOption::create(['name' => 'DragonFire','value' => '#BC4F00','additional_price' => 0]);
$option34 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen0','value' => '#79846C','additional_price' => 0]);
$option35 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen2','value' => '#A5A48B','additional_price' => 0]);
$option36 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen3','value' => '#74939C','additional_price' => 0]);
$option37 = \App\Models\ProductFieldOption::create(['name' => 'WyvernPurple1','value' => '#B0A2C0','additional_price' => 0]);
$option38 = \App\Models\ProductFieldOption::create(['name' => 'WyvernBlue0','value' => '#6281A7','additional_price' => 0]);
$option39 = \App\Models\ProductFieldOption::create(['name' => 'WyvernBlue1','value' => '#485C75','additional_price' => 0]);
$option40 = \App\Models\ProductFieldOption::create(['name' => 'Medium Blue','value' => '#5FA4EA','additional_price' => 0]);
$option41 = \App\Models\ProductFieldOption::create(['name' => 'Deep Blue','value' => '#4568D4','additional_price' => 0]);
$option42 = \App\Models\ProductFieldOption::create(['name' => 'Turquoise','value' => '#00C5AB','additional_price' => 0]);
$option43 = \App\Models\ProductFieldOption::create(['name' => 'LemonLime','value' => '#A8FF44','additional_price' => 0]);
$option44 = \App\Models\ProductFieldOption::create(['name' => 'PowderBlue','value' => '#82A7FF','additional_price' => 0]);
$option45 = \App\Models\ProductFieldOption::create(['name' => 'NearWhite','value' => '#EDEDED','additional_price' => 0]);
$option46 = \App\Models\ProductFieldOption::create(['name' => 'BigFoot0','value' => '#B79683','additional_price' => 0]);
$option47 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen1','value' => '#909C79','additional_price' => 0]);
$option48 = \App\Models\ProductFieldOption::create(['name' => 'NearBlack','value' => '#515151','additional_price' => 0]);
$option49 = \App\Models\ProductFieldOption::create(['name' => 'Bigfoot0','value' => '#B79683','additional_price' => 0]);
$option50 = \App\Models\ProductFieldOption::create(['name' => 'Bigfoot4','value' => '#EADAD5','additional_price' => 0]);
$option51 = \App\Models\ProductFieldOption::create(['name' => 'Bigfoot5','value' => '#D0A794','additional_price' => 0]);
$option52 = \App\Models\ProductFieldOption::create(['name' => 'Light Pink','value' => '#E8B0FF','additional_price' => 0]);
$option53 = \App\Models\ProductFieldOption::create(['name' => 'Powder Blue','value' => '#82A7FF','additional_price' => 0]);
$option54 = \App\Models\ProductFieldOption::create(['name' => 'Glacial','value' => '#ACEAFF','additional_price' => 0]);
$option55 = \App\Models\ProductFieldOption::create(['name' => 'BigFoot4','value' => '#EADAD5','additional_price' => 0]);
$option56 = \App\Models\ProductFieldOption::create(['name' => 'Brown','value' => '#593A2A','additional_price' => 0]);
$option57 = \App\Models\ProductFieldOption::create(['name' => 'Wolf Fur','value' => '#C3B39F','additional_price' => 0]);
$option58 = \App\Models\ProductFieldOption::create(['name' => 'Dark Wolf Fur','value' => '#887666','additional_price' => 0]);
$option59 = \App\Models\ProductFieldOption::create(['name' => 'DarkWarmGray','value' => '#3B3938','additional_price' => 0]);
$option60 = \App\Models\ProductFieldOption::create(['name' => 'MediumWarmGray','value' => '#585554','additional_price' => 0]);
$option61 = \App\Models\ProductFieldOption::create(['name' => 'LightWarmGray','value' => '#9B9290','additional_price' => 0]);
$option62 = \App\Models\ProductFieldOption::create(['name' => 'BurntSienna','value' => '#7E331E','additional_price' => 0]);
$option63 = \App\Models\ProductFieldOption::create(['name' => 'DarkTurquoise','value' => '#184546','additional_price' => 0]);
$option64 = \App\Models\ProductFieldOption::create(['name' => 'MediumTurquoise','value' => '#007060','additional_price' => 0]);
$option65 = \App\Models\ProductFieldOption::create(['name' => 'GreenSlate','value' => '#40594C','additional_price' => 0]);
$option66 = \App\Models\ProductFieldOption::create(['name' => 'DarkCement','value' => '#525B56','additional_price' => 0]);
$option67 = \App\Models\ProductFieldOption::create(['name' => 'MediumAutumn','value' => '#A93000','additional_price' => 0]);
$option68 = \App\Models\ProductFieldOption::create(['name' => 'Coral','value' => '#FF5834','additional_price' => 0]);
$option69 = \App\Models\ProductFieldOption::create(['name' => 'MidnightBlue','value' => '#191D36','additional_price' => 0]);
$option70 = \App\Models\ProductFieldOption::create(['name' => 'BlackSands','value' => '#302531','additional_price' => 0]);
$option71 = \App\Models\ProductFieldOption::create(['name' => 'Cyan','value' => '#00FFFF','additional_price' => 0]);
$option72 = \App\Models\ProductFieldOption::create(['name' => 'Magenta','value' => '#FF00FF','additional_price' => 0]);
$option73 = \App\Models\ProductFieldOption::create(['name' => 'Dragonfire','value' => '#BC4F00','additional_price' => 0]);
$option74 = \App\Models\ProductFieldOption::create(['name' => 'LightPink','value' => '#E8B0FF','additional_price' => 0]);
$option75 = \App\Models\ProductFieldOption::create(['name' => 'LightAutumn','value' => '#AE7000','additional_price' => 0]);
$option76 = \App\Models\ProductFieldOption::create(['name' => 'Mustard','value' => '#949427','additional_price' => 0]);
$option77 = \App\Models\ProductFieldOption::create(['name' => 'DarkBlue','value' => '#152B3A','additional_price' => 0]);
$option78 = \App\Models\ProductFieldOption::create(['name' => 'DarkTeal','value' => '#0E404A','additional_price' => 0]);
$option79 = \App\Models\ProductFieldOption::create(['name' => 'MediumTeal','value' => '#105563','additional_price' => 0]);
$option80 = \App\Models\ProductFieldOption::create(['name' => 'DryMoss','value' => '#766E3F','additional_price' => 0]);
$_SESSION['field0']->options()->attach([$option0->id,$option1->id,$option2->id,$option3->id,$option4->id,$option5->id,$option6->id,$option7->id,$option8->id,$option9->id,$option10->id,$option11->id,$option12->id,$option13->id,$option14->id,$option15->id,$option16->id,$option17->id,$option18->id,$option19->id,$option20->id,$option21->id,$option22->id,$option23->id,$option24->id,$option25->id,$option26->id,$option27->id,$option28->id,$option29->id,$option30->id,$option31->id,$option32->id,$option33->id,$option34->id,$option35->id,$option36->id,$option37->id,$option38->id,$option39->id,$option40->id,$option41->id,$option42->id,$option43->id,$option44->id,$option45->id,$option46->id,$option47->id,$option48->id,$option49->id,$option50->id,$option51->id,$option52->id,$option53->id,$option54->id,$option55->id,$option56->id,$option57->id,$option58->id,$option59->id,$option60->id,$option61->id,$option62->id,$option63->id,$option64->id,$option65->id,$option66->id,$option67->id,$option68->id,$option69->id,$option70->id,$option71->id,$option72->id,$option73->id,$option74->id,$option75->id,$option76->id,$option77->id,$option78->id,$option79->id,$option80->id]);
}
],
[
function() {
$option0 = \App\Models\ProductFieldOption::create(['name' => 'Light Grey','value' => '#C8CACA','additional_price' => 0]);
$option1 = \App\Models\ProductFieldOption::create(['name' => 'Dark Grey','value' => '#7B7B7B','additional_price' => 0]);
$option2 = \App\Models\ProductFieldOption::create(['name' => 'Black','value' => '#3B3B3B','additional_price' => 0]);
$option3 = \App\Models\ProductFieldOption::create(['name' => 'Light Red','value' => '#FFA8A8','additional_price' => 0]);
$option4 = \App\Models\ProductFieldOption::create(['name' => 'Light Orange','value' => '#FFB694','additional_price' => 0]);
$option5 = \App\Models\ProductFieldOption::create(['name' => 'Dark Orange','value' => '#88532F','additional_price' => 0]);
$option6 = \App\Models\ProductFieldOption::create(['name' => 'Light Yellow','value' => '#CACAA0','additional_price' => 0]);
$option7 = \App\Models\ProductFieldOption::create(['name' => 'Dark Yellow','value' => '#94946C','additional_price' => 0]);
$option8 = \App\Models\ProductFieldOption::create(['name' => 'Light Blue','value' => '#D9E0FF','additional_price' => 0]);
$option9 = \App\Models\ProductFieldOption::create(['name' => 'Light Purple','value' => '#E4D9FF','additional_price' => 0]);
$option10 = \App\Models\ProductFieldOption::create(['name' => 'Light Brown','value' => '#FFE0BA','additional_price' => 0]);
$option11 = \App\Models\ProductFieldOption::create(['name' => 'Medium Brown','value' => '#948575','additional_price' => 0]);
$option12 = \App\Models\ProductFieldOption::create(['name' => 'Dark Brown','value' => '#594E41','additional_price' => 0]);
$option13 = \App\Models\ProductFieldOption::create(['name' => 'Darker Grey','value' => '#595959','additional_price' => 0]);
$option14 = \App\Models\ProductFieldOption::create(['name' => 'Light Green','value' => '#E0FFE0','additional_price' => 0]);
$option15 = \App\Models\ProductFieldOption::create(['name' => 'Medium Green','value' => '#799479','additional_price' => 0]);
$option16 = \App\Models\ProductFieldOption::create(['name' => 'BigFoot5','value' => '#D0A794','additional_price' => 0]);
$option17 = \App\Models\ProductFieldOption::create(['name' => 'WolfFur','value' => '#C3B39F','additional_price' => 0]);
$option18 = \App\Models\ProductFieldOption::create(['name' => 'DragonBase0','value' => '#A0664B','additional_price' => 0]);
$option19 = \App\Models\ProductFieldOption::create(['name' => 'DragonBase1','value' => '#CB7956','additional_price' => 0]);
$option20 = \App\Models\ProductFieldOption::create(['name' => 'DragonFire','value' => '#BC4F00','additional_price' => 0]);
$option21 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen0','value' => '#79846C','additional_price' => 0]);
$option22 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen2','value' => '#A5A48B','additional_price' => 0]);
$option23 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen3','value' => '#74939C','additional_price' => 0]);
$option24 = \App\Models\ProductFieldOption::create(['name' => 'WyvernPurple0','value' => '#787496','additional_price' => 0]);
$option25 = \App\Models\ProductFieldOption::create(['name' => 'WyvernPurple1','value' => '#B0A2C0','additional_price' => 0]);
$option26 = \App\Models\ProductFieldOption::create(['name' => 'WyvernBlue0','value' => '#6281A7','additional_price' => 0]);
$option27 = \App\Models\ProductFieldOption::create(['name' => 'WyvernBlue1','value' => '#485C75','additional_price' => 0]);
$option28 = \App\Models\ProductFieldOption::create(['name' => 'Medium Blue','value' => '#5FA4EA','additional_price' => 0]);
$option29 = \App\Models\ProductFieldOption::create(['name' => 'Deep Blue','value' => '#4568D4','additional_price' => 0]);
$option30 = \App\Models\ProductFieldOption::create(['name' => 'LightPink','value' => '#E8B0FF','additional_price' => 0]);
$option31 = \App\Models\ProductFieldOption::create(['name' => 'DeepPink','value' => '#FF119A','additional_price' => 0]);
$option32 = \App\Models\ProductFieldOption::create(['name' => 'Coral','value' => '#FF5834','additional_price' => 0]);
$option33 = \App\Models\ProductFieldOption::create(['name' => 'Mint','value' => '#38E985','additional_price' => 0]);
$option34 = \App\Models\ProductFieldOption::create(['name' => 'Lavender','value' => '#BD77BE','additional_price' => 0]);
$option35 = \App\Models\ProductFieldOption::create(['name' => 'Glacial','value' => '#ACEAFF','additional_price' => 0]);
$option36 = \App\Models\ProductFieldOption::create(['name' => 'Dark Green','value' => '#224122','additional_price' => 0]);
$option37 = \App\Models\ProductFieldOption::create(['name' => 'BigFoot0','value' => '#B79683','additional_price' => 0]);
$option38 = \App\Models\ProductFieldOption::create(['name' => 'Albino','value' => '#FFFFFF','additional_price' => 0]);
$option39 = \App\Models\ProductFieldOption::create(['name' => 'NearWhite','value' => '#EDEDED','additional_price' => 0]);
$option40 = \App\Models\ProductFieldOption::create(['name' => 'NearBlack','value' => '#515151','additional_price' => 0]);
$option41 = \App\Models\ProductFieldOption::create(['name' => 'Dark Red','value' => '#592B2B','additional_price' => 0]);
$option42 = \App\Models\ProductFieldOption::create(['name' => 'Bigfoot0','value' => '#B79683','additional_price' => 0]);
$option43 = \App\Models\ProductFieldOption::create(['name' => 'Bigfoot4','value' => '#EADAD5','additional_price' => 0]);
$option44 = \App\Models\ProductFieldOption::create(['name' => 'Bigfoot5','value' => '#D0A794','additional_price' => 0]);
$option45 = \App\Models\ProductFieldOption::create(['name' => 'DarkWolfFur','value' => '#887666','additional_price' => 0]);
$option46 = \App\Models\ProductFieldOption::create(['name' => 'Dark Blue','value' => '#394263','additional_price' => 0]);
$option47 = \App\Models\ProductFieldOption::create(['name' => 'Dark Purple','value' => '#403459','additional_price' => 0]);
$option48 = \App\Models\ProductFieldOption::create(['name' => 'BigFoot4','value' => '#EADAD5','additional_price' => 0]);
$option49 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen1','value' => '#909C79','additional_price' => 0]);
$option50 = \App\Models\ProductFieldOption::create(['name' => 'Red','value' => '#FF0000','additional_price' => 0]);
$option51 = \App\Models\ProductFieldOption::create(['name' => 'MediumWarmGray','value' => '#585554','additional_price' => 0]);
$option52 = \App\Models\ProductFieldOption::create(['name' => 'LightWarmGray','value' => '#9B9290','additional_price' => 0]);
$option53 = \App\Models\ProductFieldOption::create(['name' => 'BurntSienna','value' => '#7E331E','additional_price' => 0]);
$option54 = \App\Models\ProductFieldOption::create(['name' => 'Peach','value' => '#FFA73A','additional_price' => 0]);
$option55 = \App\Models\ProductFieldOption::create(['name' => 'LightAutumn','value' => '#AE7000','additional_price' => 0]);
$option56 = \App\Models\ProductFieldOption::create(['name' => 'Cream','value' => '#F4FFC0','additional_price' => 0]);
$option57 = \App\Models\ProductFieldOption::create(['name' => 'Brown','value' => '#593A2A','additional_price' => 0]);
$option58 = \App\Models\ProductFieldOption::create(['name' => 'DarkWarmGray','value' => '#3B3938','additional_price' => 0]);
$option59 = \App\Models\ProductFieldOption::create(['name' => 'White','value' => '#FFFFFF','additional_price' => 0]);
$option60 = \App\Models\ProductFieldOption::create(['name' => 'MediumTurquoise','value' => '#007060','additional_price' => 0]);
$option61 = \App\Models\ProductFieldOption::create(['name' => 'LightCement','value' => '#8AA196','additional_price' => 0]);
$option62 = \App\Models\ProductFieldOption::create(['name' => 'Green','value' => '#00FF00','additional_price' => 0]);
$option63 = \App\Models\ProductFieldOption::create(['name' => 'Yellow','value' => '#FFFF00','additional_price' => 0]);
$option64 = \App\Models\ProductFieldOption::create(['name' => 'Cyan','value' => '#00FFFF','additional_price' => 0]);
$option65 = \App\Models\ProductFieldOption::create(['name' => 'Magenta','value' => '#FF00FF','additional_price' => 0]);
$option66 = \App\Models\ProductFieldOption::create(['name' => 'Turquoise','value' => '#00C5AB','additional_price' => 0]);
$option67 = \App\Models\ProductFieldOption::create(['name' => 'Vermillion','value' => '#EF3100','additional_price' => 0]);
$option68 = \App\Models\ProductFieldOption::create(['name' => 'Orange','value' => '#FF7F00','additional_price' => 0]);
$option69 = \App\Models\ProductFieldOption::create(['name' => 'LemonLime','value' => '#A8FF44','additional_price' => 0]);
$option70 = \App\Models\ProductFieldOption::create(['name' => 'Jade','value' => '#008840','additional_price' => 0]);
$option71 = \App\Models\ProductFieldOption::create(['name' => 'MediumLavender','value' => '#853587','additional_price' => 0]);
$option72 = \App\Models\ProductFieldOption::create(['name' => 'PowderBlue','value' => '#82A7FF','additional_price' => 0]);
$option73 = \App\Models\ProductFieldOption::create(['name' => 'Custard','value' => '#C0BD5E','additional_price' => 0]);
$_SESSION['field1']->options()->attach([$option0->id,$option1->id,$option2->id,$option3->id,$option4->id,$option5->id,$option6->id,$option7->id,$option8->id,$option9->id,$option10->id,$option11->id,$option12->id,$option13->id,$option14->id,$option15->id,$option16->id,$option17->id,$option18->id,$option19->id,$option20->id,$option21->id,$option22->id,$option23->id,$option24->id,$option25->id,$option26->id,$option27->id,$option28->id,$option29->id,$option30->id,$option31->id,$option32->id,$option33->id,$option34->id,$option35->id,$option36->id,$option37->id,$option38->id,$option39->id,$option40->id,$option41->id,$option42->id,$option43->id,$option44->id,$option45->id,$option46->id,$option47->id,$option48->id,$option49->id,$option50->id,$option51->id,$option52->id,$option53->id,$option54->id,$option55->id,$option56->id,$option57->id,$option58->id,$option59->id,$option60->id,$option61->id,$option62->id,$option63->id,$option64->id,$option65->id,$option66->id,$option67->id,$option68->id,$option69->id,$option70->id,$option71->id,$option72->id,$option73->id]);
}
],
[
function() {
$option0 = \App\Models\ProductFieldOption::create(['name' => 'Light Grey','value' => '#C8CACA','additional_price' => 0]);
$option1 = \App\Models\ProductFieldOption::create(['name' => 'Black','value' => '#3B3B3B','additional_price' => 0]);
$option2 = \App\Models\ProductFieldOption::create(['name' => 'Light Red','value' => '#FFA8A8','additional_price' => 0]);
$option3 = \App\Models\ProductFieldOption::create(['name' => 'Light Orange','value' => '#FFB694','additional_price' => 0]);
$option4 = \App\Models\ProductFieldOption::create(['name' => 'Light Yellow','value' => '#CACAA0','additional_price' => 0]);
$option5 = \App\Models\ProductFieldOption::create(['name' => 'Light Green','value' => '#C0FFBA','additional_price' => 0]);
$option6 = \App\Models\ProductFieldOption::create(['name' => 'Medium Green','value' => '#799479','additional_price' => 0]);
$option7 = \App\Models\ProductFieldOption::create(['name' => 'Light Blue','value' => '#D9E0FF','additional_price' => 0]);
$option8 = \App\Models\ProductFieldOption::create(['name' => 'Light Purple','value' => '#E4D9FF','additional_price' => 0]);
$option9 = \App\Models\ProductFieldOption::create(['name' => 'Light Brown','value' => '#FFE0BA','additional_price' => 0]);
$option10 = \App\Models\ProductFieldOption::create(['name' => 'Medium Brown','value' => '#948575','additional_price' => 0]);
$option11 = \App\Models\ProductFieldOption::create(['name' => 'Dark Grey','value' => '#7B7B7B','additional_price' => 0]);
$option12 = \App\Models\ProductFieldOption::create(['name' => 'Dark Red','value' => '#592B2B','additional_price' => 0]);
$option13 = \App\Models\ProductFieldOption::create(['name' => 'Dark Orange','value' => '#88532F','additional_price' => 0]);
$option14 = \App\Models\ProductFieldOption::create(['name' => 'Dark Yellow','value' => '#94946C','additional_price' => 0]);
$option15 = \App\Models\ProductFieldOption::create(['name' => 'Dark Brown','value' => '#594E41','additional_price' => 0]);
$option16 = \App\Models\ProductFieldOption::create(['name' => 'Darker Grey','value' => '#595959','additional_price' => 0]);
$option17 = \App\Models\ProductFieldOption::create(['name' => 'Dark Green','value' => '#224122','additional_price' => 0]);
$option18 = \App\Models\ProductFieldOption::create(['name' => 'Dark Blue','value' => '#394263','additional_price' => 0]);
$option19 = \App\Models\ProductFieldOption::create(['name' => 'Dark Purple','value' => '#403459','additional_price' => 0]);
$option20 = \App\Models\ProductFieldOption::create(['name' => 'White','value' => '#FFFFFF','additional_price' => 0]);
$option21 = \App\Models\ProductFieldOption::create(['name' => 'Cyan','value' => '#00FFFF','additional_price' => 0]);
$option22 = \App\Models\ProductFieldOption::create(['name' => 'Magenta','value' => '#FF00FF','additional_price' => 0]);
$option23 = \App\Models\ProductFieldOption::create(['name' => 'Medium Blue','value' => '#5FA4EA','additional_price' => 0]);
$option24 = \App\Models\ProductFieldOption::create(['name' => 'Albino','value' => '#FFFFFF','additional_price' => 0]);
$option25 = \App\Models\ProductFieldOption::create(['name' => 'BigFoot0','value' => '#B79683','additional_price' => 0]);
$option26 = \App\Models\ProductFieldOption::create(['name' => 'BigFoot5','value' => '#D0A794','additional_price' => 0]);
$option27 = \App\Models\ProductFieldOption::create(['name' => 'WolfFur','value' => '#C3B39F','additional_price' => 0]);
$option28 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen3','value' => '#74939C','additional_price' => 0]);
$option29 = \App\Models\ProductFieldOption::create(['name' => 'DragonBase0','value' => '#A0664B','additional_price' => 0]);
$option30 = \App\Models\ProductFieldOption::create(['name' => 'DragonBase1','value' => '#CB7956','additional_price' => 0]);
$option31 = \App\Models\ProductFieldOption::create(['name' => 'DragonFire','value' => '#BC4F00','additional_price' => 0]);
$option32 = \App\Models\ProductFieldOption::create(['name' => 'WyvernPurple1','value' => '#B0A2C0','additional_price' => 0]);
$option33 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen1','value' => '#909C79','additional_price' => 0]);
$option34 = \App\Models\ProductFieldOption::create(['name' => 'WyvernBlue0','value' => '#6281A7','additional_price' => 0]);
$option35 = \App\Models\ProductFieldOption::create(['name' => 'NearWhite','value' => '#EDEDED','additional_price' => 0]);
$option36 = \App\Models\ProductFieldOption::create(['name' => 'Turquoise','value' => '#00C5AB','additional_price' => 0]);
$option37 = \App\Models\ProductFieldOption::create(['name' => 'Light Pink','value' => '#E8B0FF','additional_price' => 0]);
$option38 = \App\Models\ProductFieldOption::create(['name' => 'Powder Blue','value' => '#82A7FF','additional_price' => 0]);
$option39 = \App\Models\ProductFieldOption::create(['name' => 'Glacial','value' => '#ACEAFF','additional_price' => 0]);
$option40 = \App\Models\ProductFieldOption::create(['name' => 'DarkWolfFur','value' => '#887666','additional_price' => 0]);
$option41 = \App\Models\ProductFieldOption::create(['name' => 'NearBlack','value' => '#515151','additional_price' => 0]);
$option42 = \App\Models\ProductFieldOption::create(['name' => 'Bigfoot5','value' => '#D0A794','additional_price' => 0]);
$option43 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen2','value' => '#A5A48B','additional_price' => 0]);
$option44 = \App\Models\ProductFieldOption::create(['name' => 'WyvernPurple0','value' => '#787496','additional_price' => 0]);
$option45 = \App\Models\ProductFieldOption::create(['name' => 'Dark Wolf Fur','value' => '#887666','additional_price' => 0]);
$option46 = \App\Models\ProductFieldOption::create(['name' => 'BigFoot4','value' => '#EADAD5','additional_price' => 0]);
$option47 = \App\Models\ProductFieldOption::create(['name' => 'Brown','value' => '#593A2A','additional_price' => 0]);
$option48 = \App\Models\ProductFieldOption::create(['name' => 'DarkWarmGray','value' => '#3B3938','additional_price' => 0]);
$option49 = \App\Models\ProductFieldOption::create(['name' => 'MediumWarmGray','value' => '#585554','additional_price' => 0]);
$option50 = \App\Models\ProductFieldOption::create(['name' => 'LightWarmGray','value' => '#9B9290','additional_price' => 0]);
$option51 = \App\Models\ProductFieldOption::create(['name' => 'BurntSienna','value' => '#7E331E','additional_price' => 0]);
$option52 = \App\Models\ProductFieldOption::create(['name' => 'Custard','value' => '#C0BD5E','additional_price' => 0]);
$option53 = \App\Models\ProductFieldOption::create(['name' => 'Cream','value' => '#F4FFC0','additional_price' => 0]);
$option54 = \App\Models\ProductFieldOption::create(['name' => 'Deep Blue','value' => '#4568D4','additional_price' => 0]);
$option55 = \App\Models\ProductFieldOption::create(['name' => 'WyvernBlue1','value' => '#485C75','additional_price' => 0]);
$option56 = \App\Models\ProductFieldOption::create(['name' => 'Bigfoot0','value' => '#B79683','additional_price' => 0]);
$option57 = \App\Models\ProductFieldOption::create(['name' => 'Bigfoot4','value' => '#EADAD5','additional_price' => 0]);
$option58 = \App\Models\ProductFieldOption::create(['name' => 'LightCement','value' => '#8AA196','additional_price' => 0]);
$option59 = \App\Models\ProductFieldOption::create(['name' => 'LightPink','value' => '#E8B0FF','additional_price' => 0]);
$option60 = \App\Models\ProductFieldOption::create(['name' => 'MediumAutumn','value' => '#A93000','additional_price' => 0]);
$option61 = \App\Models\ProductFieldOption::create(['name' => 'Coral','value' => '#FF5834','additional_price' => 0]);
$option62 = \App\Models\ProductFieldOption::create(['name' => 'Peach','value' => '#FFA73A','additional_price' => 0]);
$option63 = \App\Models\ProductFieldOption::create(['name' => 'LightAutumn','value' => '#AE7000','additional_price' => 0]);
$option64 = \App\Models\ProductFieldOption::create(['name' => 'Mint','value' => '#38E985','additional_price' => 0]);
$option65 = \App\Models\ProductFieldOption::create(['name' => 'LeafGreen','value' => '#5B9725','additional_price' => 0]);
$option66 = \App\Models\ProductFieldOption::create(['name' => 'Lavender','value' => '#BD77BE','additional_price' => 0]);
$option67 = \App\Models\ProductFieldOption::create(['name' => 'Teal','value' => '#14849C','additional_price' => 0]);
$option68 = \App\Models\ProductFieldOption::create(['name' => 'PowderBlue','value' => '#82A7FF','additional_price' => 0]);
$option69 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen0','value' => '#79846C','additional_price' => 0]);
$option70 = \App\Models\ProductFieldOption::create(['name' => 'DarkMagenta','value' => '#B70042','additional_price' => 0]);
$option71 = \App\Models\ProductFieldOption::create(['name' => 'LemonLime','value' => '#A8FF44','additional_price' => 0]);
$option72 = \App\Models\ProductFieldOption::create(['name' => 'BlackSands','value' => '#302531','additional_price' => 0]);
$_SESSION['field2']->options()->attach([$option0->id,$option1->id,$option2->id,$option3->id,$option4->id,$option5->id,$option6->id,$option7->id,$option8->id,$option9->id,$option10->id,$option11->id,$option12->id,$option13->id,$option14->id,$option15->id,$option16->id,$option17->id,$option18->id,$option19->id,$option20->id,$option21->id,$option22->id,$option23->id,$option24->id,$option25->id,$option26->id,$option27->id,$option28->id,$option29->id,$option30->id,$option31->id,$option32->id,$option33->id,$option34->id,$option35->id,$option36->id,$option37->id,$option38->id,$option39->id,$option40->id,$option41->id,$option42->id,$option43->id,$option44->id,$option45->id,$option46->id,$option47->id,$option48->id,$option49->id,$option50->id,$option51->id,$option52->id,$option53->id,$option54->id,$option55->id,$option56->id,$option57->id,$option58->id,$option59->id,$option60->id,$option61->id,$option62->id,$option63->id,$option64->id,$option65->id,$option66->id,$option67->id,$option68->id,$option69->id,$option70->id,$option71->id,$option72->id]);
}
],
[
function() {
$option0 = \App\Models\ProductFieldOption::create(['name' => 'Light Red','value' => '#FFA8A8','additional_price' => 0]);
$option1 = \App\Models\ProductFieldOption::create(['name' => 'Light Orange','value' => '#FFB694','additional_price' => 0]);
$option2 = \App\Models\ProductFieldOption::create(['name' => 'Light Yellow','value' => '#CACAA0','additional_price' => 0]);
$option3 = \App\Models\ProductFieldOption::create(['name' => 'Light Green','value' => '#E0FFE0','additional_price' => 0]);
$option4 = \App\Models\ProductFieldOption::create(['name' => 'Light Blue','value' => '#D9E0FF','additional_price' => 0]);
$option5 = \App\Models\ProductFieldOption::create(['name' => 'Light Purple','value' => '#E4D9FF','additional_price' => 0]);
$option6 = \App\Models\ProductFieldOption::create(['name' => 'Light Brown','value' => '#FFE0BA','additional_price' => 0]);
$option7 = \App\Models\ProductFieldOption::create(['name' => 'Medium Brown','value' => '#948575','additional_price' => 0]);
$option8 = \App\Models\ProductFieldOption::create(['name' => 'DragonBase1','value' => '#CB7956','additional_price' => 0]);
$option9 = \App\Models\ProductFieldOption::create(['name' => 'Dark Grey','value' => '#7B7B7B','additional_price' => 0]);
$option10 = \App\Models\ProductFieldOption::create(['name' => 'Black','value' => '#3B3B3B','additional_price' => 0]);
$option11 = \App\Models\ProductFieldOption::create(['name' => 'Dark Red','value' => '#592B2B','additional_price' => 0]);
$option12 = \App\Models\ProductFieldOption::create(['name' => 'Dark Orange','value' => '#88532F','additional_price' => 0]);
$option13 = \App\Models\ProductFieldOption::create(['name' => 'Dark Yellow','value' => '#94946C','additional_price' => 0]);
$option14 = \App\Models\ProductFieldOption::create(['name' => 'Dark Brown','value' => '#594E41','additional_price' => 0]);
$option15 = \App\Models\ProductFieldOption::create(['name' => 'Darker Grey','value' => '#595959','additional_price' => 0]);
$option16 = \App\Models\ProductFieldOption::create(['name' => 'Medium Green','value' => '#799479','additional_price' => 0]);
$option17 = \App\Models\ProductFieldOption::create(['name' => 'Dark Green','value' => '#224122','additional_price' => 0]);
$option18 = \App\Models\ProductFieldOption::create(['name' => 'Dark Blue','value' => '#394263','additional_price' => 0]);
$option19 = \App\Models\ProductFieldOption::create(['name' => 'Dark Purple','value' => '#403459','additional_price' => 0]);
$option20 = \App\Models\ProductFieldOption::create(['name' => 'White','value' => '#FFFFFF','additional_price' => 0]);
$option21 = \App\Models\ProductFieldOption::create(['name' => 'Light Grey','value' => '#C8CACA','additional_price' => 0]);
$option22 = \App\Models\ProductFieldOption::create(['name' => 'BigFoot5','value' => '#D0A794','additional_price' => 0]);
$option23 = \App\Models\ProductFieldOption::create(['name' => 'WolfFur','value' => '#C3B39F','additional_price' => 0]);
$option24 = \App\Models\ProductFieldOption::create(['name' => 'DragonBase0','value' => '#A0664B','additional_price' => 0]);
$option25 = \App\Models\ProductFieldOption::create(['name' => 'DragonFire','value' => '#BC4F00','additional_price' => 0]);
$option26 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen0','value' => '#79846C','additional_price' => 0]);
$option27 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen2','value' => '#A5A48B','additional_price' => 0]);
$option28 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen3','value' => '#74939C','additional_price' => 0]);
$option29 = \App\Models\ProductFieldOption::create(['name' => 'WyvernPurple0','value' => '#787496','additional_price' => 0]);
$option30 = \App\Models\ProductFieldOption::create(['name' => 'WyvernPurple1','value' => '#B0A2C0','additional_price' => 0]);
$option31 = \App\Models\ProductFieldOption::create(['name' => 'WyvernBlue0','value' => '#6281A7','additional_price' => 0]);
$option32 = \App\Models\ProductFieldOption::create(['name' => 'WyvernBlue1','value' => '#485C75','additional_price' => 0]);
$option33 = \App\Models\ProductFieldOption::create(['name' => 'Medium Blue','value' => '#5FA4EA','additional_price' => 0]);
$option34 = \App\Models\ProductFieldOption::create(['name' => 'Deep Blue','value' => '#4568D4','additional_price' => 0]);
$option35 = \App\Models\ProductFieldOption::create(['name' => 'NearWhite','value' => '#EDEDED','additional_price' => 0]);
$option36 = \App\Models\ProductFieldOption::create(['name' => 'Cyan','value' => '#00FFFF','additional_price' => 0]);
$option37 = \App\Models\ProductFieldOption::create(['name' => 'Magenta','value' => '#FF00FF','additional_price' => 0]);
$option38 = \App\Models\ProductFieldOption::create(['name' => 'Albino','value' => '#FFFFFF','additional_price' => 0]);
$option39 = \App\Models\ProductFieldOption::create(['name' => 'BigFoot0','value' => '#B79683','additional_price' => 0]);
$option40 = \App\Models\ProductFieldOption::create(['name' => 'BigFoot4','value' => '#EADAD5','additional_price' => 0]);
$option41 = \App\Models\ProductFieldOption::create(['name' => 'DarkWolfFur','value' => '#887666','additional_price' => 0]);
$option42 = \App\Models\ProductFieldOption::create(['name' => 'Yellow','value' => '#FFFF00','additional_price' => 0]);
$option43 = \App\Models\ProductFieldOption::create(['name' => 'Brown','value' => '#593A2A','additional_price' => 0]);
$option44 = \App\Models\ProductFieldOption::create(['name' => 'NearBlack','value' => '#515151','additional_price' => 0]);
$option45 = \App\Models\ProductFieldOption::create(['name' => 'DarkWarmGray','value' => '#3B3938','additional_price' => 0]);
$option46 = \App\Models\ProductFieldOption::create(['name' => 'MediumWarmGray','value' => '#585554','additional_price' => 0]);
$option47 = \App\Models\ProductFieldOption::create(['name' => 'LightWarmGray','value' => '#9B9290','additional_price' => 0]);
$option48 = \App\Models\ProductFieldOption::create(['name' => 'BurntSienna','value' => '#7E331E','additional_price' => 0]);
$option49 = \App\Models\ProductFieldOption::create(['name' => 'BlackSands','value' => '#302531','additional_price' => 0]);
$option50 = \App\Models\ProductFieldOption::create(['name' => 'PowderBlue','value' => '#82A7FF','additional_price' => 0]);
$option51 = \App\Models\ProductFieldOption::create(['name' => 'Cream','value' => '#F4FFC0','additional_price' => 0]);
$option52 = \App\Models\ProductFieldOption::create(['name' => 'Bigfoot0','value' => '#B79683','additional_price' => 0]);
$option53 = \App\Models\ProductFieldOption::create(['name' => 'Bigfoot4','value' => '#EADAD5','additional_price' => 0]);
$option54 = \App\Models\ProductFieldOption::create(['name' => 'LightAutumn','value' => '#AE7000','additional_price' => 0]);
$option55 = \App\Models\ProductFieldOption::create(['name' => 'Teal','value' => '#14849C','additional_price' => 0]);
$option56 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen1','value' => '#909C79','additional_price' => 0]);
$option57 = \App\Models\ProductFieldOption::create(['name' => 'MediumTurquoise','value' => '#007060','additional_price' => 0]);
$option58 = \App\Models\ProductFieldOption::create(['name' => 'LightCement','value' => '#8AA196','additional_price' => 0]);
$option59 = \App\Models\ProductFieldOption::create(['name' => 'LightPink','value' => '#E8B0FF','additional_price' => 0]);
$option60 = \App\Models\ProductFieldOption::create(['name' => 'Peach','value' => '#FFA73A','additional_price' => 0]);
$_SESSION['field3']->options()->attach([$option0->id,$option1->id,$option2->id,$option3->id,$option4->id,$option5->id,$option6->id,$option7->id,$option8->id,$option9->id,$option10->id,$option11->id,$option12->id,$option13->id,$option14->id,$option15->id,$option16->id,$option17->id,$option18->id,$option19->id,$option20->id,$option21->id,$option22->id,$option23->id,$option24->id,$option25->id,$option26->id,$option27->id,$option28->id,$option29->id,$option30->id,$option31->id,$option32->id,$option33->id,$option34->id,$option35->id,$option36->id,$option37->id,$option38->id,$option39->id,$option40->id,$option41->id,$option42->id,$option43->id,$option44->id,$option45->id,$option46->id,$option47->id,$option48->id,$option49->id,$option50->id,$option51->id,$option52->id,$option53->id,$option54->id,$option55->id,$option56->id,$option57->id,$option58->id,$option59->id,$option60->id]);
}
],
[
function() {
$option0 = \App\Models\ProductFieldOption::create(['name' => 'Light Red','value' => '#FFA8A8','additional_price' => 0]);
$option1 = \App\Models\ProductFieldOption::create(['name' => 'Light Orange','value' => '#FFB694','additional_price' => 0]);
$option2 = \App\Models\ProductFieldOption::create(['name' => 'Light Yellow','value' => '#CACAA0','additional_price' => 0]);
$option3 = \App\Models\ProductFieldOption::create(['name' => 'Light Green','value' => '#E0FFE0','additional_price' => 0]);
$option4 = \App\Models\ProductFieldOption::create(['name' => 'Light Purple','value' => '#E4D9FF','additional_price' => 0]);
$option5 = \App\Models\ProductFieldOption::create(['name' => 'Light Brown','value' => '#FFE0BA','additional_price' => 0]);
$option6 = \App\Models\ProductFieldOption::create(['name' => 'DarkWolfFur','value' => '#887666','additional_price' => 0]);
$option7 = \App\Models\ProductFieldOption::create(['name' => 'WyvernPurple1','value' => '#B0A2C0','additional_price' => 0]);
$option8 = \App\Models\ProductFieldOption::create(['name' => 'Light Grey','value' => '#C8CACA','additional_price' => 0]);
$option9 = \App\Models\ProductFieldOption::create(['name' => 'Dark Grey','value' => '#7B7B7B','additional_price' => 0]);
$option10 = \App\Models\ProductFieldOption::create(['name' => 'Black','value' => '#3B3B3B','additional_price' => 0]);
$option11 = \App\Models\ProductFieldOption::create(['name' => 'Dark Red','value' => '#592B2B','additional_price' => 0]);
$option12 = \App\Models\ProductFieldOption::create(['name' => 'Dark Orange','value' => '#88532F','additional_price' => 0]);
$option13 = \App\Models\ProductFieldOption::create(['name' => 'Dark Yellow','value' => '#94946C','additional_price' => 0]);
$option14 = \App\Models\ProductFieldOption::create(['name' => 'Medium Green','value' => '#799479','additional_price' => 0]);
$option15 = \App\Models\ProductFieldOption::create(['name' => 'Dark Green','value' => '#224122','additional_price' => 0]);
$option16 = \App\Models\ProductFieldOption::create(['name' => 'Medium Brown','value' => '#948575','additional_price' => 0]);
$option17 = \App\Models\ProductFieldOption::create(['name' => 'Dark Brown','value' => '#594E41','additional_price' => 0]);
$option18 = \App\Models\ProductFieldOption::create(['name' => 'Darker Grey','value' => '#595959','additional_price' => 0]);
$option19 = \App\Models\ProductFieldOption::create(['name' => 'Light Blue','value' => '#D9E0FF','additional_price' => 0]);
$option20 = \App\Models\ProductFieldOption::create(['name' => 'Dark Blue','value' => '#394263','additional_price' => 0]);
$option21 = \App\Models\ProductFieldOption::create(['name' => 'Dark Purple','value' => '#403459','additional_price' => 0]);
$option22 = \App\Models\ProductFieldOption::create(['name' => 'Albino','value' => '#FFFFFF','additional_price' => 0]);
$option23 = \App\Models\ProductFieldOption::create(['name' => 'White','value' => '#FFFFFF','additional_price' => 0]);
$option24 = \App\Models\ProductFieldOption::create(['name' => 'BigFoot5','value' => '#D0A794','additional_price' => 0]);
$option25 = \App\Models\ProductFieldOption::create(['name' => 'WolfFur','value' => '#C3B39F','additional_price' => 0]);
$option26 = \App\Models\ProductFieldOption::create(['name' => 'DragonBase0','value' => '#A0664B','additional_price' => 0]);
$option27 = \App\Models\ProductFieldOption::create(['name' => 'DragonBase1','value' => '#CB7956','additional_price' => 0]);
$option28 = \App\Models\ProductFieldOption::create(['name' => 'DragonFire','value' => '#BC4F00','additional_price' => 0]);
$option29 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen0','value' => '#79846C','additional_price' => 0]);
$option30 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen2','value' => '#A5A48B','additional_price' => 0]);
$option31 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen3','value' => '#74939C','additional_price' => 0]);
$option32 = \App\Models\ProductFieldOption::create(['name' => 'WyvernPurple0','value' => '#787496','additional_price' => 0]);
$option33 = \App\Models\ProductFieldOption::create(['name' => 'WyvernBlue0','value' => '#6281A7','additional_price' => 0]);
$option34 = \App\Models\ProductFieldOption::create(['name' => 'WyvernBlue1','value' => '#485C75','additional_price' => 0]);
$option35 = \App\Models\ProductFieldOption::create(['name' => 'Medium Blue','value' => '#5FA4EA','additional_price' => 0]);
$option36 = \App\Models\ProductFieldOption::create(['name' => 'Deep Blue','value' => '#4568D4','additional_price' => 0]);
$option37 = \App\Models\ProductFieldOption::create(['name' => 'BigFoot4','value' => '#EADAD5','additional_price' => 0]);
$option38 = \App\Models\ProductFieldOption::create(['name' => 'LightPink','value' => '#E8B0FF','additional_price' => 0]);
$option39 = \App\Models\ProductFieldOption::create(['name' => 'PowderBlue','value' => '#82A7FF','additional_price' => 0]);
$option40 = \App\Models\ProductFieldOption::create(['name' => 'Glacial','value' => '#ACEAFF','additional_price' => 0]);
$option41 = \App\Models\ProductFieldOption::create(['name' => 'Custard','value' => '#C0BD5E','additional_price' => 0]);
$option42 = \App\Models\ProductFieldOption::create(['name' => 'Cream','value' => '#F4FFC0','additional_price' => 0]);
$option43 = \App\Models\ProductFieldOption::create(['name' => 'NearWhite','value' => '#EDEDED','additional_price' => 0]);
$option44 = \App\Models\ProductFieldOption::create(['name' => 'BigFoot0','value' => '#B79683','additional_price' => 0]);
$option45 = \App\Models\ProductFieldOption::create(['name' => 'Bigfoot0','value' => '#B79683','additional_price' => 0]);
$option46 = \App\Models\ProductFieldOption::create(['name' => 'Bigfoot4','value' => '#EADAD5','additional_price' => 0]);
$option47 = \App\Models\ProductFieldOption::create(['name' => 'Bigfoot5','value' => '#D0A794','additional_price' => 0]);
$option48 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen1','value' => '#909C79','additional_price' => 0]);
$option49 = \App\Models\ProductFieldOption::create(['name' => 'Turquoise','value' => '#00C5AB','additional_price' => 0]);
$option50 = \App\Models\ProductFieldOption::create(['name' => 'Light Pink','value' => '#E8B0FF','additional_price' => 0]);
$option51 = \App\Models\ProductFieldOption::create(['name' => 'Powder Blue','value' => '#82A7FF','additional_price' => 0]);
$option52 = \App\Models\ProductFieldOption::create(['name' => 'NearBlack','value' => '#515151','additional_price' => 0]);
$option53 = \App\Models\ProductFieldOption::create(['name' => 'Brown','value' => '#593A2A','additional_price' => 0]);
$option54 = \App\Models\ProductFieldOption::create(['name' => 'MediumWarmGray','value' => '#585554','additional_price' => 0]);
$option55 = \App\Models\ProductFieldOption::create(['name' => 'LightWarmGray','value' => '#9B9290','additional_price' => 0]);
$option56 = \App\Models\ProductFieldOption::create(['name' => 'BurntSienna','value' => '#7E331E','additional_price' => 0]);
$option57 = \App\Models\ProductFieldOption::create(['name' => 'Peach','value' => '#FFA73A','additional_price' => 0]);
$option58 = \App\Models\ProductFieldOption::create(['name' => 'LightAutumn','value' => '#AE7000','additional_price' => 0]);
$option59 = \App\Models\ProductFieldOption::create(['name' => 'DarkWarmGray','value' => '#3B3938','additional_price' => 0]);
$option60 = \App\Models\ProductFieldOption::create(['name' => 'LightCement','value' => '#8AA196','additional_price' => 0]);
$option61 = \App\Models\ProductFieldOption::create(['name' => 'Yellow','value' => '#FFFF00','additional_price' => 0]);
$option62 = \App\Models\ProductFieldOption::create(['name' => 'Red','value' => '#FF0000','additional_price' => 0]);
$option63 = \App\Models\ProductFieldOption::create(['name' => 'Blue','value' => '#0000FF','additional_price' => 0]);
$option64 = \App\Models\ProductFieldOption::create(['name' => 'Green','value' => '#00FF00','additional_price' => 0]);
$option65 = \App\Models\ProductFieldOption::create(['name' => 'Cyan','value' => '#00FFFF','additional_price' => 0]);
$option66 = \App\Models\ProductFieldOption::create(['name' => 'Magenta','value' => '#FF00FF','additional_price' => 0]);
$option67 = \App\Models\ProductFieldOption::create(['name' => 'Dragonfire','value' => '#BC4F00','additional_price' => 0]);
$option68 = \App\Models\ProductFieldOption::create(['name' => 'MediumAutumn','value' => '#A93000','additional_price' => 0]);
$option69 = \App\Models\ProductFieldOption::create(['name' => 'Coral','value' => '#FF5834','additional_price' => 0]);
$option70 = \App\Models\ProductFieldOption::create(['name' => 'Mustard','value' => '#949427','additional_price' => 0]);
$option71 = \App\Models\ProductFieldOption::create(['name' => 'Mint','value' => '#38E985','additional_price' => 0]);
$option72 = \App\Models\ProductFieldOption::create(['name' => 'LeafGreen','value' => '#5B9725','additional_price' => 0]);
$option73 = \App\Models\ProductFieldOption::create(['name' => 'Lavender','value' => '#BD77BE','additional_price' => 0]);
$option74 = \App\Models\ProductFieldOption::create(['name' => 'Teal','value' => '#14849C','additional_price' => 0]);
$option75 = \App\Models\ProductFieldOption::create(['name' => 'MediumTurquoise','value' => '#007060','additional_price' => 0]);
$_SESSION['field4']->options()->attach([$option0->id,$option1->id,$option2->id,$option3->id,$option4->id,$option5->id,$option6->id,$option7->id,$option8->id,$option9->id,$option10->id,$option11->id,$option12->id,$option13->id,$option14->id,$option15->id,$option16->id,$option17->id,$option18->id,$option19->id,$option20->id,$option21->id,$option22->id,$option23->id,$option24->id,$option25->id,$option26->id,$option27->id,$option28->id,$option29->id,$option30->id,$option31->id,$option32->id,$option33->id,$option34->id,$option35->id,$option36->id,$option37->id,$option38->id,$option39->id,$option40->id,$option41->id,$option42->id,$option43->id,$option44->id,$option45->id,$option46->id,$option47->id,$option48->id,$option49->id,$option50->id,$option51->id,$option52->id,$option53->id,$option54->id,$option55->id,$option56->id,$option57->id,$option58->id,$option59->id,$option60->id,$option61->id,$option62->id,$option63->id,$option64->id,$option65->id,$option66->id,$option67->id,$option68->id,$option69->id,$option70->id,$option71->id,$option72->id,$option73->id,$option74->id,$option75->id]);
}
],
[
function() {
$option0 = \App\Models\ProductFieldOption::create(['name' => 'Light Red','value' => '#FFA8A8','additional_price' => 0]);
$option1 = \App\Models\ProductFieldOption::create(['name' => 'Light Orange','value' => '#FFB694','additional_price' => 0]);
$option2 = \App\Models\ProductFieldOption::create(['name' => 'Light Yellow','value' => '#CACAA0','additional_price' => 0]);
$option3 = \App\Models\ProductFieldOption::create(['name' => 'Light Green','value' => '#E0FFE0','additional_price' => 0]);
$option4 = \App\Models\ProductFieldOption::create(['name' => 'Light Purple','value' => '#E4D9FF','additional_price' => 0]);
$option5 = \App\Models\ProductFieldOption::create(['name' => 'Medium Brown','value' => '#948575','additional_price' => 0]);
$option6 = \App\Models\ProductFieldOption::create(['name' => 'WyvernPurple1','value' => '#B0A2C0','additional_price' => 0]);
$option7 = \App\Models\ProductFieldOption::create(['name' => 'Light Grey','value' => '#C8CACA','additional_price' => 0]);
$option8 = \App\Models\ProductFieldOption::create(['name' => 'Dark Grey','value' => '#7B7B7B','additional_price' => 0]);
$option9 = \App\Models\ProductFieldOption::create(['name' => 'Black','value' => '#3B3B3B','additional_price' => 0]);
$option10 = \App\Models\ProductFieldOption::create(['name' => 'Dark Red','value' => '#592B2B','additional_price' => 0]);
$option11 = \App\Models\ProductFieldOption::create(['name' => 'Dark Orange','value' => '#88532F','additional_price' => 0]);
$option12 = \App\Models\ProductFieldOption::create(['name' => 'Dark Yellow','value' => '#94946C','additional_price' => 0]);
$option13 = \App\Models\ProductFieldOption::create(['name' => 'Medium Green','value' => '#799479','additional_price' => 0]);
$option14 = \App\Models\ProductFieldOption::create(['name' => 'Dark Green','value' => '#224122','additional_price' => 0]);
$option15 = \App\Models\ProductFieldOption::create(['name' => 'Light Brown','value' => '#FFE0BA','additional_price' => 0]);
$option16 = \App\Models\ProductFieldOption::create(['name' => 'Dark Brown','value' => '#594E41','additional_price' => 0]);
$option17 = \App\Models\ProductFieldOption::create(['name' => 'Darker Grey','value' => '#595959','additional_price' => 0]);
$option18 = \App\Models\ProductFieldOption::create(['name' => 'Light Blue','value' => '#D9E0FF','additional_price' => 0]);
$option19 = \App\Models\ProductFieldOption::create(['name' => 'Dark Blue','value' => '#394263','additional_price' => 0]);
$option20 = \App\Models\ProductFieldOption::create(['name' => 'Dark Purple','value' => '#403459','additional_price' => 0]);
$option21 = \App\Models\ProductFieldOption::create(['name' => 'Albino','value' => '#FFFFFF','additional_price' => 0]);
$option22 = \App\Models\ProductFieldOption::create(['name' => 'White','value' => '#FFFFFF','additional_price' => 0]);
$option23 = \App\Models\ProductFieldOption::create(['name' => 'BigFoot5','value' => '#D0A794','additional_price' => 0]);
$option24 = \App\Models\ProductFieldOption::create(['name' => 'WolfFur','value' => '#C3B39F','additional_price' => 0]);
$option25 = \App\Models\ProductFieldOption::create(['name' => 'DragonBase0','value' => '#A0664B','additional_price' => 0]);
$option26 = \App\Models\ProductFieldOption::create(['name' => 'DragonBase1','value' => '#CB7956','additional_price' => 0]);
$option27 = \App\Models\ProductFieldOption::create(['name' => 'DragonFire','value' => '#BC4F00','additional_price' => 0]);
$option28 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen0','value' => '#79846C','additional_price' => 0]);
$option29 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen2','value' => '#A5A48B','additional_price' => 0]);
$option30 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen3','value' => '#74939C','additional_price' => 0]);
$option31 = \App\Models\ProductFieldOption::create(['name' => 'WyvernPurple0','value' => '#787496','additional_price' => 0]);
$option32 = \App\Models\ProductFieldOption::create(['name' => 'WyvernBlue0','value' => '#6281A7','additional_price' => 0]);
$option33 = \App\Models\ProductFieldOption::create(['name' => 'WyvernBlue1','value' => '#485C75','additional_price' => 0]);
$option34 = \App\Models\ProductFieldOption::create(['name' => 'Medium Blue','value' => '#5FA4EA','additional_price' => 0]);
$option35 = \App\Models\ProductFieldOption::create(['name' => 'Deep Blue','value' => '#4568D4','additional_price' => 0]);
$option36 = \App\Models\ProductFieldOption::create(['name' => 'LightPink','value' => '#E8B0FF','additional_price' => 0]);
$option37 = \App\Models\ProductFieldOption::create(['name' => 'DeepPink','value' => '#FF119A','additional_price' => 0]);
$option38 = \App\Models\ProductFieldOption::create(['name' => 'Coral','value' => '#FF5834','additional_price' => 0]);
$option39 = \App\Models\ProductFieldOption::create(['name' => 'Mint','value' => '#38E985','additional_price' => 0]);
$option40 = \App\Models\ProductFieldOption::create(['name' => 'Jade','value' => '#008840','additional_price' => 0]);
$option41 = \App\Models\ProductFieldOption::create(['name' => 'Lavender','value' => '#BD77BE','additional_price' => 0]);
$option42 = \App\Models\ProductFieldOption::create(['name' => 'Glacial','value' => '#ACEAFF','additional_price' => 0]);
$option43 = \App\Models\ProductFieldOption::create(['name' => 'BigFoot0','value' => '#B79683','additional_price' => 0]);
$option44 = \App\Models\ProductFieldOption::create(['name' => 'BigFoot4','value' => '#EADAD5','additional_price' => 0]);
$option45 = \App\Models\ProductFieldOption::create(['name' => 'NearBlack','value' => '#515151','additional_price' => 0]);
$option46 = \App\Models\ProductFieldOption::create(['name' => 'Bigfoot0','value' => '#B79683','additional_price' => 0]);
$option47 = \App\Models\ProductFieldOption::create(['name' => 'Bigfoot4','value' => '#EADAD5','additional_price' => 0]);
$option48 = \App\Models\ProductFieldOption::create(['name' => 'Bigfoot5','value' => '#D0A794','additional_price' => 0]);
$option49 = \App\Models\ProductFieldOption::create(['name' => 'DragonGreen1','value' => '#909C79','additional_price' => 0]);
$option50 = \App\Models\ProductFieldOption::create(['name' => 'NearWhite','value' => '#EDEDED','additional_price' => 0]);
$option51 = \App\Models\ProductFieldOption::create(['name' => 'Turquoise','value' => '#00C5AB','additional_price' => 0]);
$option52 = \App\Models\ProductFieldOption::create(['name' => 'Light Pink','value' => '#E8B0FF','additional_price' => 0]);
$option53 = \App\Models\ProductFieldOption::create(['name' => 'Powder Blue','value' => '#82A7FF','additional_price' => 0]);
$option54 = \App\Models\ProductFieldOption::create(['name' => 'DarkWolfFur','value' => '#887666','additional_price' => 0]);
$option55 = \App\Models\ProductFieldOption::create(['name' => 'Cyan','value' => '#00FFFF','additional_price' => 0]);
$option56 = \App\Models\ProductFieldOption::create(['name' => 'Brown','value' => '#593A2A','additional_price' => 0]);
$option57 = \App\Models\ProductFieldOption::create(['name' => 'DarkWarmGray','value' => '#3B3938','additional_price' => 0]);
$option58 = \App\Models\ProductFieldOption::create(['name' => 'MediumWarmGray','value' => '#585554','additional_price' => 0]);
$option59 = \App\Models\ProductFieldOption::create(['name' => 'LightWarmGray','value' => '#9B9290','additional_price' => 0]);
$option60 = \App\Models\ProductFieldOption::create(['name' => 'BurntSienna','value' => '#7E331E','additional_price' => 0]);
$option61 = \App\Models\ProductFieldOption::create(['name' => 'Cream','value' => '#F4FFC0','additional_price' => 0]);
$option62 = \App\Models\ProductFieldOption::create(['name' => 'MediumTurquoise','value' => '#007060','additional_price' => 0]);
$option63 = \App\Models\ProductFieldOption::create(['name' => 'LightCement','value' => '#8AA196','additional_price' => 0]);
$option64 = \App\Models\ProductFieldOption::create(['name' => 'Peach','value' => '#FFA73A','additional_price' => 0]);
$option65 = \App\Models\ProductFieldOption::create(['name' => 'Blue','value' => '#0000FF','additional_price' => 0]);
$option66 = \App\Models\ProductFieldOption::create(['name' => 'Green','value' => '#00FF00','additional_price' => 0]);
$option67 = \App\Models\ProductFieldOption::create(['name' => 'DarkTurquoise','value' => '#184546','additional_price' => 0]);
$option68 = \App\Models\ProductFieldOption::create(['name' => 'MediumAutumn','value' => '#A93000','additional_price' => 0]);
$option69 = \App\Models\ProductFieldOption::create(['name' => 'LightAutumn','value' => '#AE7000','additional_price' => 0]);
$option70 = \App\Models\ProductFieldOption::create(['name' => 'Mustard','value' => '#949427','additional_price' => 0]);
$option71 = \App\Models\ProductFieldOption::create(['name' => 'MidnightBlue','value' => '#191D36','additional_price' => 0]);
$option72 = \App\Models\ProductFieldOption::create(['name' => 'DarkBlue','value' => '#152B3A','additional_price' => 0]);
$option73 = \App\Models\ProductFieldOption::create(['name' => 'BlackSands','value' => '#302531','additional_price' => 0]);
$option74 = \App\Models\ProductFieldOption::create(['name' => 'LeafGreen','value' => '#5B9725','additional_price' => 0]);
$option75 = \App\Models\ProductFieldOption::create(['name' => 'DarkLavender','value' => '#5E275F','additional_price' => 0]);
$option76 = \App\Models\ProductFieldOption::create(['name' => 'DarkTeal','value' => '#0E404A','additional_price' => 0]);
$option77 = \App\Models\ProductFieldOption::create(['name' => 'MediumTeal','value' => '#105563','additional_price' => 0]);
$option78 = \App\Models\ProductFieldOption::create(['name' => 'Teal','value' => '#14849C','additional_price' => 0]);
$option79 = \App\Models\ProductFieldOption::create(['name' => 'PowderBlue','value' => '#82A7FF','additional_price' => 0]);
$_SESSION['field5']->options()->attach([$option0->id,$option1->id,$option2->id,$option3->id,$option4->id,$option5->id,$option6->id,$option7->id,$option8->id,$option9->id,$option10->id,$option11->id,$option12->id,$option13->id,$option14->id,$option15->id,$option16->id,$option17->id,$option18->id,$option19->id,$option20->id,$option21->id,$option22->id,$option23->id,$option24->id,$option25->id,$option26->id,$option27->id,$option28->id,$option29->id,$option30->id,$option31->id,$option32->id,$option33->id,$option34->id,$option35->id,$option36->id,$option37->id,$option38->id,$option39->id,$option40->id,$option41->id,$option42->id,$option43->id,$option44->id,$option45->id,$option46->id,$option47->id,$option48->id,$option49->id,$option50->id,$option51->id,$option52->id,$option53->id,$option54->id,$option55->id,$option56->id,$option57->id,$option58->id,$option59->id,$option60->id,$option61->id,$option62->id,$option63->id,$option64->id,$option65->id,$option66->id,$option67->id,$option68->id,$option69->id,$option70->id,$option71->id,$option72->id,$option73->id,$option74->id,$option75->id,$option76->id,$option77->id,$option78->id,$option79->id]);
}
],
];
